#at the moment the mongo-express cant see the mongodb

version: "3.5"

services:


  flask_app:
    container_name: flask_app
    image: flask_app
    build: ./flask_app
    ports:
      - '5000:5000'
    networks:
      - archeo_net
    volumes:
      - '~/uploads:/app/app/uploads'


networks:
  archeo_net:
    name: archeo_net
    driver: bridge
