#at the moment the mongo-express cant see the mongodb

version: "3.5"

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - archeo_net

  flask_app:
    container_name: flask_app
    image: flask_app
    build: ./flask_app
    ports:
      - '5000:5000'
    networks:
      - archeo_net
    volumes:
      - '~/uploads:/app/app/uploads'

  model_runner_app:
    container_name: model_runner_app
    image: model_runner_app
    build: ./model_runner_app
    networks:
      - archeo_net

networks:
  archeo_net:
    name: archeo_net
    driver: bridge
